#!/bin/bash

# Get Names of users
cat /etc/passwd | grep '/home/' | grep -v 'cups\|syslog\|mysql\|mongodb' | \
cut -d':' -f1 > /tmp/homes.list

function runByUsers {
	# $1 is default folder of user
	# $2 is name of user
	cd $1
    panels="$1/.config/lxpanel/Lubuntu/panels/"
	runuser -l $2 -c "mkdir -p $panels"
	runuser -l $2 -c "cp -rf /tmp/lubuntu-w10-taskbar/left $panels"
    runuser -l $2 -c "cp -rf /tmp/lubuntu-w10-taskbar/panel $panels"

	lxsession="$1/.config/lxsession/Lubuntu/"
	runuser -l $2 -c "mkdir -p $lxsession"
	runuser -l $2 -c "touch $lxsession/autostart"
	runuser -l $2 -c "sed -i \"s/taskbar-hotkey-enable//g\" $lxsession/autostart"
	runuser -l $2 -c "echo \"taskbar-hotkey-enable\" >> $lxsession/autostart"

	runuser -l $2 -c "cp -rf /tmp/lxde-win-theme-apply/.config $1/"
	runuser -l $2 -c "cp -rf /tmp/lxde-win-theme-apply/.gimp-2.8 $1/"
}

while read USUARIO; do
	runByUsers "/home/$USUARIO" "$USUARIO"
 	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
 	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
 	fi
done < /tmp/homes.list
runByUsers "/etc/skel" "root"

# Lightdm Greeter
cat << EOF > /etc/lightdm/lightdm-gtk-greeter.conf
[greeter]
background = /usr/share/lubuntu/wallpapers/wx_login.png
theme-name = Windows 10 forLxde
icon-theme-name = win10-icons
font-name = DejaVu Sans 10
user-background = false

EOF

cd /usr/share/lubuntu/wallpapers/
if [ -f 1804-lubuntu-default-wallpaper.png ]; then
	mv 1804-lubuntu-default-wallpaper.png lubuntu-original-wallpaper.png
	mv wx_wallpaper.png 1804-lubuntu-default-wallpaper.png
fi
